### ISSUE TITLE
Repeating a download after invalidating the originally used token

### ISSUE THREAD

**Issue by grahamperrin** [download-directory/download-directory.github.io#10]
I (foolishly) didn't keep a note of my first ever token, which I used at https://download-directory.github.io/?url=https://github.com/QWERTYUIOPYOZO/ReFont/tree/master/src in Waterfox. The original token no longer exists. 

Now whenever I aim to repeat that download, I get just this: 

![2018-03-25 11 19 03](https://user-images.githubusercontent.com/192271/37873976-ad7552ac-301e-11e8-8f71-83505b7852ad.png)

– not progressing to a download. 

When I click _token_, a more recently generated token is not accepted (AFAIR the bullets, in the field, appear red). 

As a workaround I can visit https://download-directory.github.io/?url=https://github.com/QWERTYUIOPYOZO/ReFont/tree/master/src in Firefox but I'm puzzling about how I can get it to work, again, in Waterfox. 

Any suggestions? 

(I already toyed with removal of cookies.)

TIA

**Comment by bfred-it** [comment]
Error handling is part of #6, but the new token should be saved anyway. If the bullets appear red then you're probably copying the token incorrectly because the color is handled by HTML5 validation, which accepts only hexadecimal characters. For example a extra space will turn it red.

Anyway to remove the old one you can clear the `localStorage` with `localStorage.clear()` in your console

**Comment by grahamperrin** [comment]
Thanks! I had previously aimed to remove storage but (again, my bad) I looked in the `download-directory.github.io` area. 

Found: 

![2018-03-25 11 35 34](https://user-images.githubusercontent.com/192271/37874144-2baf61e2-3021-11e8-90c8-888d5b25636f.png)

Following clearance, my first attempt to download didn't work. 

I carefully pasted a more recent token, with bullets appearing green then <kbd>Control</kbd>-<kbd>F5</kbd> seemed to do the trick.
