### ISSUE TITLE
Doesn't work for branches with slashes

### ISSUE THREAD

**Issue by MiniDigger** [download-directory/download-directory.github.io#35]
It tries to GET https://api.github.com/repos/PaperMC/Paper/git/trees/feature?recursive=1 which returns 404 (Not Found), while I initiated the download from his link https://github.com/PaperMC/Paper/tree/feature/mcp/mcp

**Comment by fregante** [comment]
That’s right, the URL doesn’t tell me whether `mcp` is still part of the branch or not, so we just guess it’s a folder, because that’s the most common situation. 

If you’re a Refined GitHub user however this could be resolved by making `download-directory` accept a pre-parsed URL:

``` 
?user=PaperMC&repository=Paper&path=mcp&ref=feature/mcp 
``` 

Refined GitHub can parse this information directly from the DOM rather than from the URL
